#!/usr/bin/env bash

set -e

vault="$1"
email="$2"

if [ -z "$vault" ] || [ -z "$email" ]; then
  echo 'usage: op-file-restore <vault> <email>'
  exit 1
fi

echo "Signing in to $vault 1Password vault"
echo
echo -n "Secret key: "
read -s secretkey
echo
echo

session=$(op signin "$vault" "$email" "$secretkey" --output=raw)
files=$(env "OP_SESSION_$vault=$session" op list documents | jq -rc '. | map(select((.trashed == "N") and (.overview.tags) and any(.overview.tags[]; contains("sync")))) | .[]')

while read -r file; do
  uuid=$(echo "$file" | jq -r '.uuid')
  _filename=$(echo "$file" | jq -r '.overview.title')
  filename=${_filename/#\~/$HOME}
  tarred=$(echo "$file" | jq -r 'any(.overview.tags[]; contains("sync:tar"))')

  if [ ! -z "$uuid" ]; then
    echo "Restoring $filename"

    if [ "$tarred" == "true" ]; then
      mkdir -p "$filename"
      env "OP_SESSION_$vault=$session" sh -c "op get document $uuid | tar -xvz -C $filename"
    else
      mkdir -p "$(dirname "$filename")"
      env "OP_SESSION_$vault=$session" sh -c "op get document $uuid > $filename"
    fi
  fi
done <<< "$files"
