#!/usr/bin/env bash

set -e

echo "Enable Biometric Unlock for CLI in 1Password before continuing"

op signin

files=$(op document list --format json | jq -rc '. | map(select((.tags) and any(.tags[]; contains("sync")))) | .[]')

while read -r file; do
  uuid=$(echo "$file" | jq -r '.id')
  _filename=$(echo "$file" | jq -r '.title')
  filename=${_filename/#\~/$HOME}
  tarred=$(echo "$file" | jq -r 'any(.tags[]; contains("sync:tar"))')

  if [ ! -z "$uuid" ]; then
    echo "Restoring $filename"

    if [ "$tarred" == "true" ]; then
      mkdir -p "$filename"
      op document get $uuid | tar -xvz -C $filename
    else
      mkdir -p "$(dirname "$filename")"
      op document get $uuid --output $filename
    fi
  fi
done <<< "$files"
